# Region where the stack will be deployed
aws_region: "us-west-1"

# Network mask from where the bastion may be joined
aws_allow_ssh_from: "0.0.0.0/0"

# SSH public key which is installed by default on the host
aws_key_name: "dmetzler"

# Name of the stack + deployment profile.
# The real name for the Cloudformation stack will be for instance `rancher-dev`
rancher_stackname: "rancher"
deployment_profile: "dev"


# Adress where Rancher will be available
rancher_endpoint: "rancherdev.io.nuxeo.com"

# The Cloudformation script can automatically setup Route53 to point
# the two ELB of the setup, but it needs to know the hosted zone.
# Currently Rancher and Agents DNS name must be in the same zone
aws_hostedzone_name: "io.nuxeo.com"
rancher_agent_endpoint: "*.dev.io.nuxeo.com"


# Setup of the agent clusters. For each cluster you can define differents 
# parameters
rancher_agent_clusters:
  default:
    # Number of agent hosts in that group
    size: 1
    # Type of EC2 instance in that group
    ec2_instance_type: t2.large
    # Storage allcated for each server
    ec2_storage: 30
    # Project token that will be used to register 
    rancher_project_token: B64F080D160014784341:1480064400000:Y88o3ACI0UQeM9SNXemsid4avU
    # Rancher tags that will be set on the agents
    rancher_agent_tags: "pool=default, storage=large"

  other:
    size: 2
    ec2_instance_type: t2.large
    ec2_storage: 20
    rancher_project_token: B64F080D160014784341:1480064400000:Y88o3ACI0UQeM9SNXemsid4avU
    rancher_agent_tags: "pool=other, storage=small"